
save_dir: "~/Dropbox/Projects/SMC/SleepingGiants"
save_prefix: "slpng_giants_"
save_postfix: ".txt"

tweets_per_file: 100

config_reload_interval: 15

track:
  -


follow:
  - "799047255378391040"
  - "896166389332848640"
  - "824680809009405952"
  - "833476151884410880"
  - "833943889362898949"
  - "805080175876722688"
  - "823203148949061633"
  - "819610854916288518"
  - "835892051338219520"
  - "828671523154227200"
  - "824214697926766592"
  - "821983380841627650"
  - "837190374447808512"
  - "861235734585409536"
  - "814465534737731584"
  - "823210782695587845"

follow_also_tracks: True

full_user_mentions: True

user_lookup_interval: 15
